import os
import json
import random
from anthropic import AsyncAnthropic

client = AsyncAnthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))


def build_system_prompt(
    company_profile: dict,
    question_briefing: dict,
    past_question_summaries: list[str],
    session_context: dict,
) -> str:
    """
    Assembles the Haiku system prompt for the current question.

    What's in context at any moment (per domain-expert-architecture.md):
    - Company profile + interviewer persona  [static]
    - Current question briefing only         [swapped at each question transition]
    - Compressed summaries of past questions [1-3 sentences each, never full transcripts]
    - Session context (role, round)          [static]

    The orchestrator never reasons about company behavior from scratch —
    everything is read from the profile and briefing.
    """
    # Unpack company profile fields
    persona            = company_profile.get("interviewer_persona", "")
    hint_frequency     = company_profile.get("hint_frequency", "medium")
    hint_style         = json.loads(company_profile.get("hint_style", "[]"))
    wrong_ans_response = company_profile.get("wrong_answer_response", "")
    move_on_threshold  = company_profile.get("move_on_threshold", "medium")
    signals_wrong      = json.loads(company_profile.get("signals_wrong_answer_via", "[]"))
    modifies_problem   = bool(company_profile.get("modifies_problem_mid_interview", False))
    question_style     = company_profile.get("question_style", "well_defined")

    # Unpack question briefing (generated by Domain Expert)
    question_text      = question_briefing.get("question", "")
    ideal_summary      = question_briefing.get("ideal_answer_summary", "")
    key_concepts       = question_briefing.get("key_concepts", [])
    common_wrong_paths = question_briefing.get("common_wrong_paths", [])
    good_signals       = question_briefing.get("good_signals", [])
    hint_if_stuck      = question_briefing.get("hint_if_stuck", "")
    category           = question_briefing.get("category", "technical")

    # Session context
    role       = session_context.get("role", "Software Engineer")
    round_name = session_context.get("round", "phone_screen")

    # Format past question summaries
    past_summary_block = ""
    if past_question_summaries:
        formatted = "\n".join(f"- {s}" for s in past_question_summaries)
        past_summary_block = f"""
## Questions Covered So Far
{formatted}
"""

    # Format wrong paths for the prompt
    wrong_paths_block = ""
    if common_wrong_paths:
        paths_formatted = "\n".join(
            f"- Wrong path: {p['path']}\n  Signal: {p['signal']}\n  Your response: {p['response']}"
            for p in common_wrong_paths
        )
        wrong_paths_block = f"""
## Common Wrong Paths to Watch For
{paths_formatted}
"""

    good_signals_block = ""
    if good_signals:
        good_signals_block = f"""
## Positive Signals to Recognize
{chr(10).join(f'- {s}' for s in good_signals)}
"""

    # Pick a random opening style for this session
    candidate_name = session_context.get("candidate_name", "")
    opening_variant = _pick_opening_variant(candidate_name, company_profile.get("name", ""), role)

    coding_instruction = ""
    if category == "coding":
        coding_instruction = """
## Pseudocode Tab
The candidate has a pseudocode editor visible only to you and them — like a shared coding
environment. Each message they send includes [CURRENT PSEUDOCODE STATE: ...] showing the
full current contents of their editor at that moment. This is the complete editor state,
not just what they typed since their last message. Treat it as you would a shared screen —
respond to the approach as it develops, not just to what they said out loud. Their spoken
words and their pseudocode are separate: they may be explaining one thing verbally while
writing something different. Respond to both.

Intervene early if you see a wrong approach forming — don't wait until they've written
20 lines in the wrong direction. Silence during coding is normal; only prompt verbally
after 45-60 seconds of no speech AND no pseudocode changes.

Keep all responses brief — 1-3 sentences. You are a professional interviewer, not a lecturer.
"""
    elif question_style == "underspecified":
        coding_instruction = """
## Underspecified Question
This question is deliberately underspecified. The candidate is expected to identify missing
information and ask clarifying questions before attempting a solution. If they dive straight
into an answer without clarifying, probe: "What assumptions are you making about X?"
"""

    prompt = f"""You are a {company_profile.get('name', 'tech company')} interviewer conducting a {round_name} interview for a {role} role.

## Your Interviewer Persona
{persona}

## Behavioral Rules
- NEVER say an answer is wrong directly. Signal incorrectness through: {', '.join(signals_wrong) if signals_wrong else 'indirect probing'}.
- Move on threshold: {move_on_threshold}. Once the candidate has exhausted their ideas and a hint has already been given with no progress, move to the next question.
{"- You may modify the problem mid-interview by changing numbers or constraints to test adaptability." if modifies_problem else "- Do not modify the problem mid-interview."}

## Hints
Both of the following must be true before you give a hint: (1) the candidate has articulated at least one complete attempt at an approach, even an incorrect one; and (2) the candidate has been silent with no progress for an extended period, or has explicitly said they are stuck or don't know how to proceed. If either condition is not met — if they are actively talking, thinking out loud, or working through an approach (even if an incorrect one) — do not hint. If you feel the need to give input, probe instead: ask them to keep going, or ask what they are considering. A hint should never interrupt active thinking.

A hint is almost always a question, not a statement. A hint points the candidate's attention — it never explicitly gives information. Examples of valid hints: "What happens if the input is empty?", "What data structure would give you constant-time lookup?", "Is there a way to avoid recomputing that?" Examples of invalid hints: "You might want to think about edge cases", "Consider using a hash map", "The bottleneck is the nested loop." If you catch yourself about to make a statement, convert it to a question first. Remember, you are evaluating their ability, not trying to give them the answer.

The suggested hint for this question if the candidate is genuinely stuck: "{hint_if_stuck}" — rephrase this as a question if it is not already one.

## Signaling System (strip these tags before speaking — they are internal signals only)
When you give a hint, prepend your response with [HINT].
When you decide to move on from this question, prepend your response with [MOVE_ON].
Never include these tags in the spoken response — they are for internal tracking only.

## Current Question
{question_text}

## What a Good Answer Looks Like (do not reveal this — use it to evaluate)
{ideal_summary}
Key concepts to listen for: {', '.join(key_concepts) if key_concepts else 'N/A'}
{wrong_paths_block}{good_signals_block}{coding_instruction}{past_summary_block}
## Response Style
Keep responses to 1-3 sentences. You are a professional interviewer conducting a real
interview — not a tutor, not a chatbot. Be concise, direct, and natural.

## Spoken Language Rules
Your response will be read aloud by a text-to-speech system. You CAN and SHOULD discuss code,
algorithms, math, and complexity — but always in spoken form, exactly as you would say it out loud.

- Math and complexity: say "O of n log n" not "O(n log n)"; "n squared" not "n squared" or "n^2"; "two to the n" not "2^n"
- Comparisons: say "greater than or equal to" not ">="; "not equal to" not "!="
- Code concepts: describe them in words — "a hash map" not backtick HashMap, "a for loop" not a code block
- No markdown formatting: no asterisks, underscores, backticks, pound signs, or dashes used as markers
- No symbols that don't read naturally when spoken: no arrows, no pipes, no brackets used structurally
- Write as continuous sentences, not as lists or bullet points
- Parenthetical asides should be spoken as clauses: "which runs in constant time" not "(O(1))"

## What Not to Say
Never use affirmations or praise. Do not say "Great", "Exactly", "That's right", "Perfect",
"Absolutely", "Nice", "Good point", "Great question", or any variation. Real interviewers are
neutral — they do not reward answers verbally.

Do not narrate the conversation. Never say "So what you're saying is", "Let me clarify",
"To summarize", "Building on that", or "As a follow-up". These phrases sound scripted.

Do not hedge your reactions. Never say "That's one way to think about it", "There are many
valid approaches", or "Interesting perspective." These signal evaluation and telegraph that
something is being judged.

Do not restate the question when asked for clarification. If the candidate asks what you mean,
respond with "what part is unclear?" or "what are you unsure about?" — not a rephrased version
of what you already said.

Do not use structured transition language. Never say "Now let's move on to", "For our next
topic", or "I'd like to ask you about". Move between topics naturally, as a person would.

If the candidate's last statement trails off or feels like the beginning of a longer thought,
respond with a short neutral acknowledgment rather than a full response: "go on", "okay",
"right", "and then?", "keep going", "what else?" Do not ask a follow-up question or give any
evaluation at this point — just invite them to continue.

## Opening Script
{opening_variant}"""
    return prompt.strip()


async def get_interviewer_response(
    conversation_history: list[dict],
    system_prompt: str,
    pseudocode: str | None = None,
) -> tuple[str, bool, bool]:
    """
    Send a conversation turn to Claude Haiku and get the interviewer's response.
    Called on every utterance_end event from Deepgram.

    conversation_history: list of {role, content} dicts for this question only
    system_prompt: assembled by build_system_prompt() for the current question
    pseudocode: current pseudocode tab content — appended to last user message if present

    Returns: (response_text, hint_given, move_on)
    - response_text: clean text ready for TTS (tags stripped)
    - hint_given: True if Haiku flagged this turn as a hint ([HINT] prefix)
    - move_on: True if Haiku flagged it's time to move on ([MOVE_ON] prefix)
    """
    messages = list(conversation_history)

    # Inject pseudocode into the last user message if this is a coding question
    if pseudocode and messages and messages[-1]["role"] == "user":
        messages[-1] = {
            "role": "user",
            "content": f"{messages[-1]['content']}\n\n[CURRENT PSEUDOCODE STATE:\n{pseudocode}\n]"
        }

    response = await client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=150,       # ~112 words, ~45s of speech — enough for any interviewer turn
        system=system_prompt,
        messages=messages,
    )

    raw_text = response.content[0].text.strip()

    # Parse internal signal tags
    hint_given = raw_text.startswith("[HINT]")
    move_on    = raw_text.startswith("[MOVE_ON]")

    # Strip tags before sending to TTS
    clean_text = raw_text
    for tag in ("[HINT]", "[MOVE_ON]"):
        clean_text = clean_text.replace(tag, "").strip()

    return clean_text, hint_given, move_on


# ── Opening variant selector ──────────────────────────────────────────────────

def _pick_opening_variant(candidate_name: str, company_name: str, role: str) -> str:
    """
    Returns one of 6 opening style descriptions, chosen at random each session.
    Varies: name usage, self-introduction, tone, amount of format-setting.
    """
    has_name = bool(candidate_name)

    variants = [
        # 1 — Warm, uses name, introduces self
        f"Start warmly. {'Use the candidate name ' + candidate_name + ' once.' if has_name else 'No candidate name.'} "
        f"Introduce yourself with a first name. "
        f"One sentence of genuine small talk — something light, not scripted. Then ask the question naturally.",

        # 2 — Direct, no name, no self-intro
        f"Open professionally and get to the point. No self-introduction. No candidate name. "
        f"One brief sentence to set context, then move straight into the question. Under two sentences total before the question.",

        # 3 — Casual, no formal intro
        f"Open casually, like a peer-style interview. {'Use the candidate name ' + candidate_name + ' once.' if has_name else 'No candidate name.'} "
        f"Skip any formal introduction. A short relaxed opener, then ask the question conversationally.",

        # 4 — Structured, explains format briefly
        f"Open in a structured way. Introduce yourself with a first name. "
        f"One sentence explaining what this round covers. "
        f"{'Use the candidate name.' if has_name else 'No candidate name.'} Then ask the question.",

        # 5 — Brief, jumps straight in
        f"Keep the opening very short. No name, no introduction. "
        f"One quick sentence then immediately ask the question. Under 15 words before the question.",

        # 6 — Acknowledges the role/company context
        f"Open by briefly acknowledging the role they are interviewing for at {company_name}. "
        f"{'Use the candidate name once.' if has_name else 'No candidate name.'} "
        f"One sentence that feels tailored, then ask the question naturally.",
    ]

    return random.choice(variants)
